### ISSUE TITLE
Small bug, cursor jumps to start of line

### ISSUE THREAD

**Issue by luckman212** [xefyrdev/obsidian-arrows#1]
Awesome little plugin! 🚀

## bug

If line contains a `>` already, and cursor is positioned to the left of it, typing `-` to complete the arrow causes cursor to jump back to the beginning of the line

## repro

- obsidian 1.4.3 (installer 1.3.7)
- arrows 1.0.1

new note, paste the following text:
```
foo > bar > baz
```

now, position cursor here:
```
foo > bar > baz
         /_________ right behind that 2nd >
```
type `-`

cursor jumps to start of line. same thing happens with `<-`

(this is worse in long paragraphs...)

**Comment by luckman212** [comment]
In your README you state that you don't accept changes or PRs. So I forked it and fixed the bug.

If you want to merge/test: 
https://github.com/xefyrdev/obsidian-arrows/compare/master...luckman212:obsidian-arrows:luckman212-fix-cursor-jump

```js
export default class ObsidianArrows extends Plugin {
	private _replaceArrowsInCurrentLine(editor: Editor): void {
		const currentLineNumber = editor.getCursor().line;
		const origCursorPos = editor.getCursor('anchor');
		const currentLineContent = editor.getLine(currentLineNumber);
		// Only run if there are arrows to be modified
		if (_hasArrows(currentLineContent)) {
			editor.setLine(currentLineNumber, _replaceArrows(currentLineContent));
			editor.setCursor(origCursorPos);
		}
	}
```

**Comment by xefyrdev** [comment]
Hello I added that to my README because I just made this to learn Obsidian plugins, I didn't think anyone would actually use it 😅

Since that bug seems kinda annoying I'll merge your PR!
