### ISSUE TITLE
No Appropriate Version Found

### ISSUE THREAD

**Issue by Aetherinox** [xefyrdev/obsidian-arrows#3]
### Issue
Is this plugin only for older version of Obsidian?

When I attempt to download it from the Plugin shop, it throws the message **"No appropriate version found"** and fails to install.

Currently running v1.3.7

Manual install works fine. 

### Request

I'd like to recommend a setting that allows us to opt out of the newline break when an arrow is replaced with the characters.

Currently when you insert an arrow, the cursor breaks to a new line and you have to go back up.
It works well if I open `main.js` and remove the line:
```js
editor.setCursor(origCursorPos);
```

**Comment by xefyrdev** [comment]
The `manifest.json` didn't have a `versions` property which was probably what was causing the "No appropriate version found".

About the cursor adding breaking to a new line, I haven't been able to reproduce it. The cursor stays on the same line for me.
