### ISSUE TITLE
Small bug, cursor jumps to end of next line

### ISSUE THREAD

**Issue by guihasparyk** [xefyrdev/obsidian-arrows#4]
That's an excellent plugin btw.

- bug
  - When I'm writing when creating arrows at the end of a line it always go to the start of the next line, and it breaks my writing flow.

- repro
  - obsidian 1.4.13 (installer 1.3.5)
  - arrows 1.0.2

**Comment by xefyrdev** [comment]
Hi, to be honest when I made this mini plugin I didn't expect that many people to download it.

However, this feature is now supported natively in Obsidian v1.4.14.
